In [1]:
import pandas as pd
import numpy as np
from config import config

def read(path):
    df = pd.read_csv(path)
    return df

In [5]:
df = read("./dataset/balanced.csv")
df = df.drop(columns = ['Unnamed: 0'])

In [33]:
V = user[["bias"]].to_numpy()
U = movie[["bias"]].to_numpy()

Unnamed: 0  userID      bias
0             0       1  0.677390
1             1       2 -0.085523
2             2       3 -1.295665
3             3       4 -0.353015
4             4       5 -0.173535
..          ...     ...       ...
605         605     606 -0.043915
606         606     607  0.140626
607         607     608 -0.339125
608         608     609 -0.325961
609         609     610  0.091362

[610 rows x 3 columns]

In [6]:
df.loc[611]

userID       6.000000
movieID    113.000000
rating      -0.467735
Name: 611, dtype: float64

In [20]:
def save(df):
    df.to_csv("./dataset/balanced.csv")
    return

def convert_to_matrix(df):
    nusers = config.nusers
    nmovies = config.nmovies
    ratings = np.zeros(shape=(nusers,nmovies))
    for i in range(len(df)):
        try:
            userID = int(df.loc[i][0]-1)
            movieID = int(df.loc[i][1]-1)
            rating = float(df.loc[i][2])
            ratings[userID, movieID] = rating
        except:
            print(i, df.loc[i][0]-1, df.loc[i][1]-1)
    return ratings

In [21]:
def learning(learning_rate, epoch, ratings):
    V = np.zeros(ratings.shape[0])
    U = np.zeros(ratings.shape[1])
    for _ in range(epoch):
        F = np.add.outer(V,U)
        gradient_V = np.sum(ratings-F, axis = 1) - 2*config.lamda*V
        gradient_U = np.sum(ratings-F, axis = 0) - 2*config.lamda*U
        V += 2*learning_rate*gradient_V
        U += 2*learning_rate*gradient_U
    return V, U

      Name  age  total
0   Parker   32     99
1    Smith   28     99
2  William   39     99


In [33]:
from random import *

V = np.array([randint(-10, 10) for i in range(20)])
U = np.array([randint(-10, 10) for i in range(10)])

In [39]:
F = np.add.outer(V,U)

In [40]:
V, U, F

(array([-2, 10,  0,  7,  0,  2, -8, -8, -3,  2, 10, -2, -6,  2,  9,  1, -9,
        -6,  5, -3]),
 array([ 2, -1, -2,  6, -8, -7,  8, -8, -7, -4]),
 array([[  0,  -3,  -4,   4, -10,  -9,   6, -10,  -9,  -6],
        [ 12,   9,   8,  16,   2,   3,  18,   2,   3,   6],
        [  2,  -1,  -2,   6,  -8,  -7,   8,  -8,  -7,  -4],
        [  9,   6,   5,  13,  -1,   0,  15,  -1,   0,   3],
        [  2,  -1,  -2,   6,  -8,  -7,   8,  -8,  -7,  -4],
        [  4,   1,   0,   8,  -6,  -5,  10,  -6,  -5,  -2],
        [ -6,  -9, -10,  -2, -16, -15,   0, -16, -15, -12],
        [ -6,  -9, -10,  -2, -16, -15,   0, -16, -15, -12],
        [ -1,  -4,  -5,   3, -11, -10,   5, -11, -10,  -7],
        [  4,   1,   0,   8,  -6,  -5,  10,  -6,  -5,  -2],
        [ 12,   9,   8,  16,   2,   3,  18,   2,   3,   6],
        [  0,  -3,  -4,   4, -10,  -9,   6, -10,  -9,  -6],
        [ -4,  -7,  -8,   0, -14, -13,   2, -14, -13, -10],
        [  4,   1,   0,   8,  -6,  -5,  10,  -6,  -5,  -2],
        [ 11

In [42]:
V.shape, U.shape, F.shape

((20,), (10,), (20, 10))

In [9]:
TEST= np.array([[  0,  -3,  -4,   4, -10,  -9,   6, -10,  -9,  -6],
                [ 12,   9,   0,  16,   2,   3,  18,   2,   3,   6],
                [  2,  -1,  -2,   0,  -8,  -7,   8,  -8,  -7,  -4],
                [  9,   6,   5,  13,  -1,   0,  15,  -1,   0,   3],
                [  2,  -1,  -2,   6,  -8,  -7,   0,  -8,  -7,  -4],
                [  4,   1,   0,   8,  -6,  -5,  10,  -6,  -5,  -2],
                [ -6,  -9, -10,  -2, -16, -15,   0, -16, -15, -12],
                [ -6,  -9, -10,  -2, -16, -15,   0, -16, -15, -12],
                [  0,  -4,  -5,   3, -11, -10,   5, -11, -10,  -7],
                [  4,   1,   0,   8,   0,  -5,  10,  -6,  -5,  -2],
                [ 12,   9,   8,  16,   2,   3,  18,   2,   3,   6],
                [  0,  -3,  -4,   4, -10,  -9,   6, -10,  -9,  -6],
                [ -4,  -7,  -8,   0, -14, -13,   2, -14, -13, -10],
                [  4,   0,   0,   8,  -6,  -5,  10,  -6,  -5,  -2],
                [ 11,   8,   7,  15,   1,   2,  17,   1,   0,   5],
                [  0,   0,  -1,   7,  -7,  -6,   9,  -7,  -6,  -3],
                [ -7, -10, -11,  -3, -17, -16,   0, -17, -16, -13],
                [ -4,  -7,  -8,   0, -14, -13,   2, -14, -13, -10],
                [  7,   0,   3,  11,  -3,  -2,  13,  -3,  -2,   1],
                [ -1,  -4,  -5,   0, -11, -10,   0, -11, -10,  -7]])

In [10]:
TEST[0]*TEST[1]

array([  0, -27,   0,  64, -20, -27, 108, -20, -27, -36])

In [12]:
A = np.nonzero(TEST[0]*TEST[1])

In [18]:
B = np.zeros(610)

In [28]:
C = np.where(TEST[, 1]==0)[0]

SyntaxError: invalid syntax (<ipython-input-28-b8abe2acd316>, line 1)

In [23]:
np.argmax(TEST[0]*TEST[1])

6

In [27]:
A[0]

array([1, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [31]:
TEST[:,1]

array([ -3,   9,  -1,   6,  -1,   1,  -9,  -9,  -4,   1,   9,  -3,  -7,
         0,   8,   0, -10,  -7,   0,  -4])

In [34]:
abs(TEST[:,1])

array([ 3,  9,  1,  6,  1,  1,  9,  9,  4,  1,  9,  3,  7,  0,  8,  0, 10,
        7,  0,  4])