In [1]:
import pandas as pd
import numpy as np
from config import config

def read(path):
    df = pd.read_csv(path)
    return df

In [2]:
df = read(config.file_path)

In [29]:
df.loc[100835]

userId        610.0
movieId    170875.0
rating          3.0
Name: 100835, dtype: float64

In [20]:
def save(df):
    df.to_csv("./dataset/balanced.csv")
    return

def convert_to_matrix(df):
    nusers = int(df.loc[len(df)-1][0])
    nmovies = int(df.loc[len(df)-1][1])
    ratings = np.zeros(shape=(nusers,nmovies))
    avg = df["rating"].mean()
    for i in range(len(df)):
        userID = int(df.loc[i][0])
        movieID = int(df.loc[i][1])
        rating = float(df.loc[i][2])
        ratings[userID, movieID] = rating - avg
    return ratings

In [21]:
def learning(learning_rate, epoch, ratings):
    V = np.zeros(ratings.shape[0])
    U = np.zeros(ratings.shape[1])
    for _ in range(epoch):
        F = np.add.outer(V,U)
        gradient_V = np.sum(ratings-F, axis = 1) - 2*config.lamda*V
        gradient_U = np.sum(ratings-F, axis = 0) - 2*config.lamda*U
        V += 2*learning_rate*gradient_V
        U += 2*learning_rate*gradient_U
    return V, U

      Name  age  total
0   Parker   32     99
1    Smith   28     99
2  William   39     99


In [33]:
from random import *

V = np.array([randint(-10, 10) for i in range(20)])
U = np.array([randint(-10, 10) for i in range(10)])

In [39]:
F = np.add.outer(V,U)

In [40]:
V, U, F

(array([-2, 10,  0,  7,  0,  2, -8, -8, -3,  2, 10, -2, -6,  2,  9,  1, -9,
        -6,  5, -3]),
 array([ 2, -1, -2,  6, -8, -7,  8, -8, -7, -4]),
 array([[  0,  -3,  -4,   4, -10,  -9,   6, -10,  -9,  -6],
        [ 12,   9,   8,  16,   2,   3,  18,   2,   3,   6],
        [  2,  -1,  -2,   6,  -8,  -7,   8,  -8,  -7,  -4],
        [  9,   6,   5,  13,  -1,   0,  15,  -1,   0,   3],
        [  2,  -1,  -2,   6,  -8,  -7,   8,  -8,  -7,  -4],
        [  4,   1,   0,   8,  -6,  -5,  10,  -6,  -5,  -2],
        [ -6,  -9, -10,  -2, -16, -15,   0, -16, -15, -12],
        [ -6,  -9, -10,  -2, -16, -15,   0, -16, -15, -12],
        [ -1,  -4,  -5,   3, -11, -10,   5, -11, -10,  -7],
        [  4,   1,   0,   8,  -6,  -5,  10,  -6,  -5,  -2],
        [ 12,   9,   8,  16,   2,   3,  18,   2,   3,   6],
        [  0,  -3,  -4,   4, -10,  -9,   6, -10,  -9,  -6],
        [ -4,  -7,  -8,   0, -14, -13,   2, -14, -13, -10],
        [  4,   1,   0,   8,  -6,  -5,  10,  -6,  -5,  -2],
        [ 11

In [42]:
V.shape, U.shape, F.shape

((20,), (10,), (20, 10))

array([[False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False,  True,  True, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True, 